/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconFxemojiBanana: typeof import('~icons/fxemoji/banana')['default']
    'IconMaterialSymbols:10k': typeof import('~icons/material-symbols/10k')['default']
    'IMaterialSymbols:10k': typeof import('~icons/material-symbols/10k')['default']
    'IMaterialSymbols:add': typeof import('~icons/material-symbols/add')['default']
    'IMaterialSymbols:cloudUpload': typeof import('~icons/material-symbols/cloud-upload')['default']
    'IMaterialSymbols:edit': typeof import('~icons/material-symbols/edit')['default']
    'IZondicons:reload': typeof import('~icons/zondicons/reload')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NP: typeof import('naive-ui')['NP']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RestaurantList: typeof import('./src/components/RestaurantList.vue')['default']
    RestaurantPick: typeof import('./src/components/RestaurantPick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
